# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01abe73e38b27bf8ee17e5af8ad56302d3af77a408f73861bec125e1424fbd90b258069567e3002cbc84f503e9f1a2d94897b39f024d04b9c9212067037327d
  image_host: 'http://localhost:3000'

test:
  secret_key_base: 03e58e3dd3e3befb0aebf23c66d9f8111663f771b3c55ca2e5e01f44547982b5b7e4764e723a300f825f9e391a6a72bdfdc143996d07e94e387eda7a0d7eb6f1
  image_host: 'http://localhost:3000'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  image_host: 'https://ibacon.herokuapp.com'
